// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"time"
)

type Account struct {
	ID             int64     `json:"id"`
	Owner          string    `json:"owner"`
	CompanyName    string    `json:"company_name"`
	Industry       string    `json:"industry"`
	TargetIndustry string    `json:"target_industry"`
	TargetPosition string    `json:"target_position"`
	TargetSize     int64     `json:"target_size"`
	CreatedAt      time.Time `json:"created_at"`
}

type Lead struct {
	ID              int64     `json:"id"`
	AccountID       int64     `json:"account_id"`
	Email           string    `json:"email"`
	TelephoneNumber string    `json:"telephone_number"`
	TargetEmail     string    `json:"target_email"`
	CompanyName     string    `json:"company_name"`
	Conversation    string    `json:"conversation"`
	CreatedAt       time.Time `json:"created_at"`
}

type User struct {
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
