// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateLead(ctx context.Context, arg CreateLeadParams) (Lead, error)
	DeleteAccount(ctx context.Context, id int64) error
	DeleteLead(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetLead(ctx context.Context, id int64) (Lead, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	ListLeads(ctx context.Context, arg ListLeadsParams) ([]Lead, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateLead(ctx context.Context, arg UpdateLeadParams) (Lead, error)
}

var _ Querier = (*Queries)(nil)
